require 'rubygems'
require_relative 'filey-diff/data-sources/aws_sdk_s3'
require_relative 'filey-diff/data-sources/file_system'
require_relative 'filey-diff/file_object'
require_relative 'filey-diff/comparison'
